config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get 'welcome/index'

  resources :projects do
    resources :discussions do
      resources :comments
    end
  end

  devise_for :members, controllers: {
    sessions: 'members/sessions'
  }

  root 'home#index'

  #this makes emails available at localhost:3000/letter_opener
  mount LetterOpenerWeb::Engine, at: '/letter_opener' #if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :replies, class_name: "Comment", foreign_key: "prompt_id"
  belongs_to :prompt, class_name: 'Comment', foreign_key: 'prompt_id', optional: true

  belongs_to :discussion
  belongs_to :member

end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :project

  has_many :participations
  has_many :members, through: :participations

  has_many :comments
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  has_many :projects, inverse_of: 'owner', foreign_key: 'owner_id'
  has_many :participations
  has_many :discussions, through: :participations
  has_many :comments

  validates :displayname, presence: true, uniqueness: {case_sensitive: false}

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :displayname, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :discussion
  belongs_to :member
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :owner, class_name: 'Member', foreign_key: 'owner_id'
  has_many :discussions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects, inverse_of: 'owner', foreign_key: 'owner_id'
  has_many :participations
  has_many :discussions, through: :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # allow devise views & controllers accept extra parameters
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = %i[displayname email password password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  layout 'base'
end

app/controllers/comments_controller.rb
class CommentsController < BaseController

    def create
      if (member_signed_in?)
        @discussion = Discussion.find(params[:discussion_id])
        @comment = @discussion.comments.create(member_id: current_member.id, discussion_id: @discussion.id, content: comment_params[:content], comment_type: 'default')
      end
      redirect_to project_discussion_path(@discussion.project, @discussion)
    end

    private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/discussions_controller.rb
class DiscussionsController < BaseController
  before_action :authenticate_member!, only: [:create, :new]

  def index
    @project = Project.find(params[:project_id])
  end
  def show
    @discussion = Discussion.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @discussion = Discussion.new
  end

  def create
    if (helpers.member_signed_in_and_owns_project?(params[:project_id]))
      @project = Project.find(params[:project_id])
      @discussion = @project.discussions.create(discussion_params)
    end

    redirect_to project_discussions_path(@project)
  end

  private def discussion_params
    params.require(:discussion).permit(:name, :goal)
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index

  end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/projects_controller.rb
class ProjectsController < BaseController
  before_action :authenticate_member!, only: [:create, :new]

  def index
     @projects=Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @member = current_member
    @member.projects.create(project_params)

    redirect_to projects_path
  end

  private def project_params
    params.require(:project).permit(:name, :exposition)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def member_signed_in_and_owns_project?(project_id)
    member_signed_in? && current_member.projects.exists?(id:  project_id)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.member.displayname %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.content %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @discussion.project, @discussion, @discussion.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/discussions/_discussion.html.erb
<p>
  <strong>Discussion Name:</strong>
  <%= link_to discussion.name, project_discussion_path(discussion.project, discussion) %> ||||
  <strong>Discussion Goal:</strong>
  <%= discussion.goal %>
</p>

app/views/discussions/index.html.erb
<% if (member_signed_in_and_owns_project?(@project.id))  %>
  <h4>
    Project Discussions: <%= link_to 'New Discussion', new_project_discussion_path(@project) %>
  </h4>
<% end %>

<%= render @project.discussions %>

<%= link_to 'Project', project_path(@project) %>

app/views/discussions/new.html.erb
<h3>New Discussion for Project: <%=@project.name %></h3>

<%= form_with(model: [ @project, @project.discussions.build ], local: true) do |form| %>
  <p>
    <%= form.label :name, 'Discussion Name'%><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :goal, 'Discussion Goal'%><br>
    <%= form.text_field :goal %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/discussions/show.html.erb
<%= render @discussion %>

<h2>Comments</h2>
<%= render @discussion.comments %>



<% if (member_signed_in?)  %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% end %>

<%= link_to 'All discussions', project_discussions_path %>

app/views/projects/_project.html.erb
<p>
  <%= link_to project.name, project_path(project)  %> - <%= project.exposition %>
</p>

app/views/projects/index.html.erb
<h2>Projects</h2>
<%= link_to 'Add new project', new_project_path %>
<%= render (@projects) %>

<%= link_to 'Back', root_path %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= form_with model: @project, local: true do |form| %>
  <p>
    <%= form.label :name, 'Project Name'%><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :exposition, 'Project Exposition'%><br>
    <%= form.text_area :exposition %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
</h1>

<h3>
  <strong>Project Exposition:</strong>
  <%= @project.exposition %>
</h3>

<%=link_to 'Project Discussions', project_discussions_path(@project) %>
<br/>

<%= link_to 'Back', projects_path %>